import AuthProvider from '@/components/AuthProvider'
import Header from '@/components/Header'
import { ThemeProvider } from '@/components/ThemeProvider'
import { cn } from '@/lib/utils'
import { GeistSans } from 'geist/font'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Notear',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={cn(GeistSans.className, "h-full grid grid-rows-[min-content_1fr]")}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Header />
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
